/**
 * Bổ sung trạm temp_rescue_station id 5000–5011 lên map độ phủ.
 * Admin: province/district từ tên cũ (sau khi suy từ lat/lng nearest ward vì *_name_old đang null trên Dev);
 * precinct suy từ lat/lng (centroid xã V1 gần nhất).
 * Chỉ các id này — không đụng snapshot khác.
 */
import type { DbStationRow } from './stationCoverageFromDb';

export const SUPPLEMENTAL_STATION_IDS = [
  5000, 5001, 5002, 5003, 5004, 5005, 5006, 5007, 5008, 5009, 5010, 5011,
] as const;

export const SUPPLEMENTAL_STATIONS: DbStationRow[] = [
  {
    id: 5000,
    code: 'RS000001',
    name: 'Gara ô tô - Máy công trình- Ép tuy ô thuỷ lực- cứu hộ giao thông (Lực Loan Mường lay)',
    address: 'Thị Xã Mường Lay, Điện Biên',
    latitude: 22.001722,
    longitude: 103.154024,
    provinceCode: 'DBI',
    districtCode: 'MLA',
    precinctCode: 'LNUA',
    areaType: null,
    partnerId: null,
    partnerCode: 'PN0000001',
    partnerName: 'Gara ô tô - Máy công trình- Ép tuy ô thuỷ lực- cứu hộ giao thông (Lực Loan Mường lay)',
    partnerType: 'NO_STANDARD',
    signingDate: null,
  },
  {
    id: 5001,
    code: 'RS000002',
    name: 'Cứu hộ giao thông An Khê - Tú Toàn',
    address: 'Thị xã An Khê, Gia Lai',
    latitude: 13.960607,
    longitude: 108.660864,
    provinceCode: 'GLA',
    districtCode: 'AKH',
    precinctCode: 'TSON',
    areaType: null,
    partnerId: null,
    partnerCode: 'PN0000002',
    partnerName: 'Cứu hộ giao thông An Khê - Tú Toàn',
    partnerType: 'NO_STANDARD',
    signingDate: null,
  },
  {
    id: 5002,
    code: 'RS000003',
    name: 'Cứu Hộ An Khê',
    address: 'Thị xã An Khê, Gia Lai',
    latitude: 13.970618,
    longitude: 108.676143,
    provinceCode: 'GLA',
    districtCode: 'AKH',
    precinctCode: 'ATAN',
    areaType: null,
    partnerId: null,
    partnerCode: 'PN0000003',
    partnerName: 'Cứu Hộ An Khê',
    partnerType: 'NO_STANDARD',
    signingDate: null,
  },
  {
    id: 5003,
    code: 'RS000004',
    name: 'Gara Đạt Phát (Sửa chữa, cứu hộ giao thông, chở máy công trình)',
    address: 'H.Ngân Sơn, Bắc Cạn',
    latitude: 22.370139,
    longitude: 105.89897,
    provinceCode: 'BKA',
    districtCode: 'NSO',
    precinctCode: 'NPHA',
    areaType: null,
    partnerId: null,
    partnerCode: 'PN0000004',
    partnerName: 'Gara Đạt Phát (Sửa chữa, cứu hộ giao thông, chở máy công trình)',
    partnerType: 'NO_STANDARD',
    signingDate: null,
  },
  {
    id: 5004,
    code: 'RS000005',
    name: 'Cứu Hộ Lốp Nguyên Lê',
    address: 'Hòa Bình, Hòa Bình',
    latitude: 20.892008,
    longitude: 105.367188,
    provinceCode: 'HBI',
    districtCode: 'THBI',
    precinctCode: 'TMIN',
    areaType: null,
    partnerId: null,
    partnerCode: 'PN0000005',
    partnerName: 'Cứu Hộ Lốp Nguyên Lê',
    partnerType: 'NO_STANDARD',
    signingDate: null,
  },
  {
    id: 5005,
    code: 'RS000006',
    name: 'Cứu hộ lốp _ắc quy 24/24',
    address: 'Hòa Bình, Hòa Bình',
    latitude: 20.899357,
    longitude: 105.408303,
    provinceCode: 'HBI',
    districtCode: 'THBI',
    precinctCode: 'TMIN',
    areaType: null,
    partnerId: null,
    partnerCode: 'PN0000006',
    partnerName: 'Cứu hộ lốp _ắc quy 24/24',
    partnerType: 'NO_STANDARD',
    signingDate: null,
  },
  {
    id: 5006,
    code: 'RS000007',
    name: 'Cứu hộ lốp xe ôtô, dịch vụ tải cẩu .kéo xe hư hỏng',
    address: 'H.Quỳ Hợp, Nghệ An',
    latitude: 19.327423,
    longitude: 105.154336,
    provinceCode: 'NAN',
    districtCode: 'QHO',
    precinctCode: 'CQUA',
    areaType: null,
    partnerId: null,
    partnerCode: 'PN0000007',
    partnerName: 'Cứu hộ lốp xe ôtô, dịch vụ tải cẩu .kéo xe hư hỏng',
    partnerType: 'NO_STANDARD',
    signingDate: null,
  },
  {
    id: 5007,
    code: 'RS000008',
    name: 'Cẩu-Cứu hộ-Vận chuyển hàng hoá',
    address: 'H.Quỳ Hợp, Nghệ An',
    latitude: 19.339318,
    longitude: 105.221675,
    provinceCode: 'NAN',
    districtCode: 'QHO',
    precinctCode: 'THO0',
    areaType: null,
    partnerId: null,
    partnerCode: 'PN0000008',
    partnerName: 'Cẩu-Cứu hộ-Vận chuyển hàng hoá',
    partnerType: 'NO_STANDARD',
    signingDate: null,
  },
  {
    id: 5008,
    code: 'RS000009',
    name: 'Phụ tùng ôtô - máy kéo TUY LOAN',
    address: 'H.Quỳ Hợp, Nghệ An',
    latitude: 19.339447,
    longitude: 105.304666,
    provinceCode: 'NAN',
    districtCode: 'QHO',
    precinctCode: 'NXUA',
    areaType: null,
    partnerId: null,
    partnerCode: 'PN0000009',
    partnerName: 'Phụ tùng ôtô - máy kéo TUY LOAN',
    partnerType: 'NO_STANDARD',
    signingDate: null,
  },
  {
    id: 5009,
    code: 'RS000010',
    name: 'Gara Ô Tô Thanh Luân - Cứu Hộ Xe 24/7',
    address: 'H.Chiêm Hóa, Tuyên Quang',
    latitude: 22.385283,
    longitude: 105.181117,
    provinceCode: 'TQU',
    districtCode: 'CHO',
    precinctCode: 'TBIN',
    areaType: null,
    partnerId: null,
    partnerCode: 'PN0000010',
    partnerName: 'Gara Ô Tô Thanh Luân - Cứu Hộ Xe 24/7',
    partnerType: 'NO_STANDARD',
    signingDate: null,
  },
  {
    id: 5010,
    code: 'RS000011',
    name: 'Cứu hộ sửu chữa oto cao tốc nội bài lào cai',
    address: 'H.Bảo Yên, Lào Cai',
    latitude: 22.202114,
    longitude: 104.367553,
    provinceCode: 'LCA',
    districtCode: 'BYE',
    precinctCode: 'BAHA',
    areaType: null,
    partnerId: null,
    partnerCode: 'PN0000011',
    partnerName: 'Cứu hộ sửu chữa oto cao tốc nội bài lào cai',
    partnerType: 'NO_STANDARD',
    signingDate: null,
  },
  {
    id: 5011,
    code: 'RS000012',
    name: 'CỨU HỘ GIAO THÔNG VĂN BÀN',
    address: 'H.Văn Bàn, Lào Cai',
    latitude: 22.084864,
    longitude: 104.260998,
    provinceCode: 'LCA',
    districtCode: 'VBA',
    precinctCode: 'KYTH',
    areaType: null,
    partnerId: null,
    partnerCode: 'PN0000012',
    partnerName: 'CỨU HỘ GIAO THÔNG VĂN BÀN',
    partnerType: 'NO_STANDARD',
    signingDate: null,
  },
];

/** Override admin chỉ cho bộ id trên (Địa chỉ cũ V1). */
export const SUPPLEMENTAL_STATION_OVERRIDES: Record<
  string,
  { provinceCode: string; districtCode: string; precinctCode: string }
> = {
  '5000': { provinceCode: 'DBI', districtCode: 'MLA', precinctCode: 'LNUA' },
  '5001': { provinceCode: 'GLA', districtCode: 'AKH', precinctCode: 'TSON' },
  '5002': { provinceCode: 'GLA', districtCode: 'AKH', precinctCode: 'ATAN' },
  '5003': { provinceCode: 'BKA', districtCode: 'NSO', precinctCode: 'NPHA' },
  '5004': { provinceCode: 'HBI', districtCode: 'THBI', precinctCode: 'TMIN' },
  '5005': { provinceCode: 'HBI', districtCode: 'THBI', precinctCode: 'TMIN' },
  '5006': { provinceCode: 'NAN', districtCode: 'QHO', precinctCode: 'CQUA' },
  '5007': { provinceCode: 'NAN', districtCode: 'QHO', precinctCode: 'THO0' },
  '5008': { provinceCode: 'NAN', districtCode: 'QHO', precinctCode: 'NXUA' },
  '5009': { provinceCode: 'TQU', districtCode: 'CHO', precinctCode: 'TBIN' },
  '5010': { provinceCode: 'LCA', districtCode: 'BYE', precinctCode: 'BAHA' },
  '5011': { provinceCode: 'LCA', districtCode: 'VBA', precinctCode: 'KYTH' },
};
