/**
 * Snapshot Dev `temp_rescue_station` (prod copy): mỗi xe INTERNAL = 1 điểm trạm nội bộ.
 * id = 10_000_000 + station_vehicle_id; name = station_name + " " + plate.
 * Tọa độ ưu tiên latitude_new/longitude_new; mã địa bàn ưu tiên *_old (V1).
 */
import type { DbStationRow } from './stationCoverageFromDb';

export const INTERNAL_VEHICLE_STATIONS: DbStationRow[] = 
[
  {
    "id": 10000151,
    "code": "CAR-ĐNB-03_51M52194",
    "name": "Carpla Service Đắk Lắk 51M52194",
    "address": "",
    "latitude": 12.633871,
    "longitude": 108.159504,
    "provinceCode": "DLA",
    "districtCode": "BMT",
    "precinctCode": "ETAM",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNG",
    "partnerName": "Carpla Service Đà Nẵng",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000152,
    "code": "CAR-ĐNB-02_51M43943",
    "name": "Carpla Service Bình Phước 51M43943",
    "address": "",
    "latitude": 11.540589,
    "longitude": 107.045259,
    "provinceCode": "BPH",
    "districtCode": "PLN",
    "precinctCode": "BPHU",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNB",
    "partnerName": "Carpla Service Đông Nam Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000153,
    "code": "CAR-ĐNB-02_51B41623",
    "name": "Carpla Service Bình Phước 51B41623",
    "address": "",
    "latitude": 11.680209,
    "longitude": 106.94168,
    "provinceCode": "BPH",
    "districtCode": "PLN",
    "precinctCode": "BPHU",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNB",
    "partnerName": "Carpla Service Đông Nam Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000154,
    "code": "CAR-ĐNB-01_51M64017",
    "name": "Carpla Service Vĩnh Phú - Bình Dương 51M64017",
    "address": "",
    "latitude": 10.878844,
    "longitude": 106.705518,
    "provinceCode": "BDU",
    "districtCode": "TAN",
    "precinctCode": "BHOA",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNB",
    "partnerName": "Carpla Service Đông Nam Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000155,
    "code": "CAR-CTO_11_51M67964",
    "name": "Carpla Service Cà Mau 51M67964",
    "address": "",
    "latitude": 9.251417,
    "longitude": 105.009256,
    "provinceCode": "CMA",
    "districtCode": "CMA",
    "precinctCode": "LVLA",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-CTO",
    "partnerName": "Carpla Service Cần Thơ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000156,
    "code": "CAR-CTO_11_51M67724",
    "name": "Carpla Service Cà Mau 51M67724",
    "address": "",
    "latitude": 9.274435,
    "longitude": 105.20582,
    "provinceCode": "CMA",
    "districtCode": "CMA",
    "precinctCode": "LVLA",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-CTO",
    "partnerName": "Carpla Service Cần Thơ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000157,
    "code": "CAR-HCM_31_51M67952",
    "name": "Carpla Service Long An 51M67952",
    "address": "",
    "latitude": 10.53826,
    "longitude": 106.416238,
    "provinceCode": "LAN",
    "districtCode": "CGI",
    "precinctCode": "LOAN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-TNB",
    "partnerName": "Carpla Service Tây Nam Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000158,
    "code": "CAR-HCM_31_51M67545",
    "name": "Carpla Service Long An 51M67545",
    "address": "",
    "latitude": 10.562893,
    "longitude": 106.394243,
    "provinceCode": "LAN",
    "districtCode": "CGI",
    "precinctCode": "LOAN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-TNB",
    "partnerName": "Carpla Service Tây Nam Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000159,
    "code": "CAR-HCM_31_30B43212",
    "name": "Carpla Service Long An 30B43212",
    "address": "",
    "latitude": 10.626423,
    "longitude": 106.256364,
    "provinceCode": "LAN",
    "districtCode": "CGI",
    "precinctCode": "LOAN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-TNB",
    "partnerName": "Carpla Service Tây Nam Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000160,
    "code": "CAR-HCM_41_51M67636",
    "name": "Carpla Service Đà Lạt 51M67636",
    "address": "",
    "latitude": 12.070254,
    "longitude": 108.398762,
    "provinceCode": "LDO",
    "districtCode": "DLA",
    "precinctCode": "0003",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNB",
    "partnerName": "Carpla Service Đông Nam Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000161,
    "code": "CAR-HCM-04_30B50161",
    "name": "Carpla Service Vũng Tàu 30B50161",
    "address": "",
    "latitude": 10.355688,
    "longitude": 107.094446,
    "provinceCode": "BRV",
    "districtCode": "VTA",
    "precinctCode": "0006",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNB",
    "partnerName": "Carpla Service Đông Nam Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000162,
    "code": "CAR-HCM-02_30B43170",
    "name": "Carpla Service Tân Phú 30B43170",
    "address": "",
    "latitude": 10.778809,
    "longitude": 106.636737,
    "provinceCode": "HCM",
    "districtCode": "TDU",
    "precinctCode": "TAPH",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HCM",
    "partnerName": "Carpla Service Hồ Chí Minh",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000163,
    "code": "CAR-HCM-02_51M64254",
    "name": "Carpla Service Tân Phú 51M64254",
    "address": "",
    "latitude": 10.772051,
    "longitude": 106.627787,
    "provinceCode": "HCM",
    "districtCode": "TDU",
    "precinctCode": "TAPH",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HCM",
    "partnerName": "Carpla Service Hồ Chí Minh",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000164,
    "code": "CAR-HN-09_51M64192",
    "name": "Carpla Service Hưng Yên 51M64192",
    "address": "",
    "latitude": 20.650927,
    "longitude": 106.059378,
    "provinceCode": "HYE",
    "districtCode": "HYE",
    "precinctCode": "HYEN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HN",
    "partnerName": "Carpla Service Hà Nội",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000165,
    "code": "CAR-HCM_91_51M65822",
    "name": "Carpla Service Tân Cảng 51M65822",
    "address": "",
    "latitude": 10.805042,
    "longitude": 106.718609,
    "provinceCode": "HCM",
    "districtCode": "TDU",
    "precinctCode": "BCHI",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HCM",
    "partnerName": "Carpla Service Hồ Chí Minh",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000166,
    "code": "CAR-ĐNG-02_51M52164",
    "name": "Carpla Service Nha Trang 51M52164",
    "address": "",
    "latitude": 12.120299,
    "longitude": 109.136083,
    "provinceCode": "KHO",
    "districtCode": "NTR",
    "precinctCode": "VTHN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNG",
    "partnerName": "Carpla Service Đà Nẵng",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000167,
    "code": "CAR-HCM_91_51M67984",
    "name": "Carpla Service Tân Cảng 51M67984",
    "address": "",
    "latitude": 10.792809,
    "longitude": 106.719125,
    "provinceCode": "HCM",
    "districtCode": "TDU",
    "precinctCode": "BCHI",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HCM",
    "partnerName": "Carpla Service Hồ Chí Minh",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000168,
    "code": "CAR-ĐNG-02_51B41654",
    "name": "Carpla Service Nha Trang 51B41654",
    "address": "",
    "latitude": 12.245397,
    "longitude": 109.045048,
    "provinceCode": "KHO",
    "districtCode": "NTR",
    "precinctCode": "VTHN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNG",
    "partnerName": "Carpla Service Đà Nẵng",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000169,
    "code": "CAR-HCM-03_30B43177",
    "name": "Carpla Service Bà Rịa 30B43177",
    "address": "",
    "latitude": 10.584186,
    "longitude": 107.265328,
    "provinceCode": "BRV",
    "districtCode": "BRI",
    "precinctCode": "LHUO",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNB",
    "partnerName": "Carpla Service Đông Nam Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000170,
    "code": "CAR-HN-08_51M64409",
    "name": "Carpla Service Nam Định 51M64409",
    "address": "",
    "latitude": 20.444704,
    "longitude": 106.167394,
    "provinceCode": "NDI",
    "districtCode": "NDI",
    "precinctCode": "NML",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐBB",
    "partnerName": "Carpla Service Đông Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000171,
    "code": "CAR-HCM-03_51M63918",
    "name": "Carpla Service Bà Rịa 51M63918",
    "address": "",
    "latitude": 10.651342,
    "longitude": 107.234711,
    "provinceCode": "BRV",
    "districtCode": "BRI",
    "precinctCode": "LHUO",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNB",
    "partnerName": "Carpla Service Đông Nam Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000172,
    "code": "CAR-HN-08_51M64427",
    "name": "Carpla Service Nam Định 51M64427",
    "address": "",
    "latitude": 20.422966,
    "longitude": 106.160136,
    "provinceCode": "NDI",
    "districtCode": "NDI",
    "precinctCode": "NML",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐBB",
    "partnerName": "Carpla Service Đông Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000173,
    "code": "CAR-HCM-04_51M64133",
    "name": "Carpla Service Vũng Tàu 51M64133",
    "address": "",
    "latitude": 10.343773,
    "longitude": 107.090862,
    "provinceCode": "BRV",
    "districtCode": "VTA",
    "precinctCode": "0006",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNB",
    "partnerName": "Carpla Service Đông Nam Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000174,
    "code": "CAR-HN-11_51M64080",
    "name": "Carpla Service Bắc Giang 51M64080",
    "address": "",
    "latitude": 21.357812,
    "longitude": 106.387119,
    "provinceCode": "BGI",
    "districtCode": "BGI",
    "precinctCode": "HVTH",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐBB",
    "partnerName": "Carpla Service Đông Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000175,
    "code": "CAR-HCM-04_51M653,95",
    "name": "Carpla Service Vũng Tàu 51M653,95",
    "address": "",
    "latitude": 10.348,
    "longitude": 107.082128,
    "provinceCode": "BRV",
    "districtCode": "VTA",
    "precinctCode": "0006",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNB",
    "partnerName": "Carpla Service Đông Nam Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000176,
    "code": "CAR-HCM_71_51M65851",
    "name": "Carpla Service Bình Thuận 51M65851",
    "address": "",
    "latitude": 11.083411,
    "longitude": 108.208156,
    "provinceCode": "BTH",
    "districtCode": "HTB",
    "precinctCode": "HTHA",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNB",
    "partnerName": "Carpla Service Đông Nam Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000177,
    "code": "CAR-ĐNG_31_51M65649",
    "name": "Carpla Service Ninh Thuận 51M65649",
    "address": "",
    "latitude": 11.41099,
    "longitude": 108.869683,
    "provinceCode": "NTH",
    "districtCode": "TNA",
    "precinctCode": "PDIN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNG",
    "partnerName": "Carpla Service Đà Nẵng",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000178,
    "code": "CAR-ĐNG_31_51M65501",
    "name": "Carpla Service Ninh Thuận 51M65501",
    "address": "",
    "latitude": 11.643081,
    "longitude": 108.910232,
    "provinceCode": "NTH",
    "districtCode": "TNA",
    "precinctCode": "PDIN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNG",
    "partnerName": "Carpla Service Đà Nẵng",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000179,
    "code": "CAR-HN-05_51M64422",
    "name": "Carpla Service Long Biên 51M64422",
    "address": "",
    "latitude": 21.049635,
    "longitude": 105.885985,
    "provinceCode": "HNO",
    "districtCode": "LBI",
    "precinctCode": "VHUN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HN",
    "partnerName": "Carpla Service Hà Nội",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000180,
    "code": "CAR-HN-05_51M65407",
    "name": "Carpla Service Long Biên 51M65407",
    "address": "",
    "latitude": 21.053578,
    "longitude": 105.904283,
    "provinceCode": "HNO",
    "districtCode": "LBI",
    "precinctCode": "VHUN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HN",
    "partnerName": "Carpla Service Hà Nội",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000181,
    "code": "CAR-HN-10_51M64131",
    "name": "Carpla Service Hòa Bình 51M64131",
    "address": "",
    "latitude": 20.683972,
    "longitude": 105.29491,
    "provinceCode": "HBI",
    "districtCode": "HBI",
    "precinctCode": "HBIN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-TBB",
    "partnerName": "Carpla Service Tây Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000182,
    "code": "CAR-HN-10_30B43151",
    "name": "Carpla Service Hòa Bình 30B43151",
    "address": "",
    "latitude": 20.87656,
    "longitude": 105.250602,
    "provinceCode": "HBI",
    "districtCode": "HBI",
    "precinctCode": "HBIN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-TBB",
    "partnerName": "Carpla Service Tây Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000183,
    "code": "CAR-NAN-03_51M64098",
    "name": "Carpla Service Hà Tĩnh 51M64098",
    "address": "",
    "latitude": 18.236264,
    "longitude": 106.072099,
    "provinceCode": "HTI",
    "districtCode": "CXU",
    "precinctCode": "CBIN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-NAN",
    "partnerName": "Carpla Service Nghệ An",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000184,
    "code": "CAR-HN_21_51M-64406",
    "name": "Carpla Service Hà Nam 51M-64406",
    "address": "",
    "latitude": 20.538019,
    "longitude": 105.93363,
    "provinceCode": "HNA",
    "districtCode": "PLY",
    "precinctCode": "PVAN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HN",
    "partnerName": "Carpla Service Hà Nội",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000185,
    "code": "CAR-HN_21_51M67691",
    "name": "Carpla Service Hà Nam 51M67691",
    "address": "",
    "latitude": 20.484949,
    "longitude": 105.782148,
    "provinceCode": "HNA",
    "districtCode": "PLY",
    "precinctCode": "PVAN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HN",
    "partnerName": "Carpla Service Hà Nội",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000186,
    "code": "CAR-NAN-03_51M64267",
    "name": "Carpla Service Hà Tĩnh 51M64267",
    "address": "",
    "latitude": 18.321382,
    "longitude": 105.918535,
    "provinceCode": "HTI",
    "districtCode": "CXU",
    "precinctCode": "CBIN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-NAN",
    "partnerName": "Carpla Service Nghệ An",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000187,
    "code": "CAR-HN-03_51M63938",
    "name": "Carpla Service Hải Phòng 51M63938",
    "address": "",
    "latitude": 20.826503,
    "longitude": 106.705814,
    "provinceCode": "HPH",
    "districtCode": "HAN",
    "precinctCode": "LDU",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐBB",
    "partnerName": "Carpla Service Đông Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000188,
    "code": "CAR-HN-03_51B41650",
    "name": "Carpla Service Hải Phòng 51B41650",
    "address": "",
    "latitude": 20.822131,
    "longitude": 106.719602,
    "provinceCode": "HPH",
    "districtCode": "HAN",
    "precinctCode": "LDU",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐBB",
    "partnerName": "Carpla Service Đông Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000189,
    "code": "CAR-ĐBB_51_51M67852",
    "name": "Carpla Service Lạng Sơn 51M67852",
    "address": "",
    "latitude": 21.75888,
    "longitude": 106.802216,
    "provinceCode": "LSO",
    "districtCode": "20",
    "precinctCode": "PKL",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐBB",
    "partnerName": "Carpla Service Đông Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000190,
    "code": "CAR-ĐNG_41_51M65874",
    "name": "Carpla Service Quảng Ngãi 51M65874",
    "address": "",
    "latitude": 15.143054,
    "longitude": 108.829668,
    "provinceCode": "QNG",
    "districtCode": "QNG",
    "precinctCode": "TQTR",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNG",
    "partnerName": "Carpla Service Đà Nẵng",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000191,
    "code": "CAR-ĐNG_41_51M67711",
    "name": "Carpla Service Quảng Ngãi 51M67711",
    "address": "",
    "latitude": 15.154297,
    "longitude": 108.800378,
    "provinceCode": "QNG",
    "districtCode": "QNG",
    "precinctCode": "TQTR",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNG",
    "partnerName": "Carpla Service Đà Nẵng",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000192,
    "code": "CAR-CTO-01_51M65381",
    "name": "Carpla Service Cần Thơ 51M65381",
    "address": "",
    "latitude": 10.001305,
    "longitude": 105.778094,
    "provinceCode": "STR",
    "districtCode": "MTU",
    "precinctCode": "HPHU",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-CTO",
    "partnerName": "Carpla Service Cần Thơ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000193,
    "code": "CAR-CTO-01_51M65404",
    "name": "Carpla Service Cần Thơ 51M65404",
    "address": "",
    "latitude": 9.98759,
    "longitude": 105.796367,
    "provinceCode": "STR",
    "districtCode": "MTU",
    "precinctCode": "HPHU",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-CTO",
    "partnerName": "Carpla Service Cần Thơ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000194,
    "code": "CAR-HN-01_51M51905",
    "name": "Carpla Service Thái Nguyên 51M51905",
    "address": "",
    "latitude": 21.737206,
    "longitude": 105.829902,
    "provinceCode": "TNG",
    "districtCode": "TNG",
    "precinctCode": "GSAN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐBB",
    "partnerName": "Carpla Service Đông Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000195,
    "code": "CAR-HN-01_51M65504",
    "name": "Carpla Service Thái Nguyên 51M65504",
    "address": "",
    "latitude": 21.588219,
    "longitude": 106.028523,
    "provinceCode": "TNG",
    "districtCode": "TNG",
    "precinctCode": "GSAN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐBB",
    "partnerName": "Carpla Service Đông Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000196,
    "code": "CAR-HN-04_51M63965",
    "name": "Carpla Service Quảng Ninh 51M63965",
    "address": "",
    "latitude": 20.962503,
    "longitude": 107.003798,
    "provinceCode": "QNI",
    "districtCode": "HLO",
    "precinctCode": "TCHA",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐBB",
    "partnerName": "Carpla Service Đông Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000197,
    "code": "CAR-HN-02_51M52007",
    "name": "Carpla Service Vĩnh Phúc 51M52007",
    "address": "",
    "latitude": 21.453873,
    "longitude": 105.51964,
    "provinceCode": "VPH",
    "districtCode": "VYE",
    "precinctCode": "NQUY",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-TBB",
    "partnerName": "Carpla Service Tây Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000198,
    "code": "CAR-HN-02_51M64103",
    "name": "Carpla Service Vĩnh Phúc 51M64103",
    "address": "",
    "latitude": 21.307459,
    "longitude": 105.594785,
    "provinceCode": "VPH",
    "districtCode": "VYE",
    "precinctCode": "NQUY",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-TBB",
    "partnerName": "Carpla Service Tây Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000199,
    "code": "CAR-ĐNG-01_30B-43210",
    "name": "Carpla Service Đà Nẵng 30B-43210",
    "address": "",
    "latitude": 16.02767,
    "longitude": 108.248129,
    "provinceCode": "DNA",
    "districtCode": "HVA",
    "precinctCode": "HPH0",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNG",
    "partnerName": "Carpla Service Đà Nẵng",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000200,
    "code": "CAR-ĐNG-01_51M-65358",
    "name": "Carpla Service Đà Nẵng 51M-65358",
    "address": "",
    "latitude": 16.011129,
    "longitude": 108.198531,
    "provinceCode": "DNA",
    "districtCode": "HVA",
    "precinctCode": "HPH0",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNG",
    "partnerName": "Carpla Service Đà Nẵng",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000201,
    "code": "TEST_01_99C97026",
    "name": "Trạm TEST (Không chọn) 99C97026",
    "address": "",
    "latitude": 21.021578,
    "longitude": 105.792868,
    "provinceCode": "HNO",
    "districtCode": "CGI",
    "precinctCode": "TLIE",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "TEST",
    "partnerName": "PARTNER TEST",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000202,
    "code": "CAR-HN_61_51M70936",
    "name": "Carpla Service Thái Bình 51M70936",
    "address": "",
    "latitude": 20.426555,
    "longitude": 106.347593,
    "provinceCode": "TBI",
    "districtCode": "TBI",
    "precinctCode": "THDA",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HN",
    "partnerName": "Carpla Service Hà Nội",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000203,
    "code": "CAR-HN-07_30B43224",
    "name": "Carpla Service Phạm Văn Đồng 30B43224",
    "address": "",
    "latitude": 21.074345,
    "longitude": 105.790375,
    "provinceCode": "HNO",
    "districtCode": "BTL",
    "precinctCode": "DNGA",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HN",
    "partnerName": "Carpla Service Hà Nội",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000204,
    "code": "CAR-NAN-02_51M63987",
    "name": "Carpla Service Nghệ An 51M63987",
    "address": "",
    "latitude": 18.691735,
    "longitude": 105.683681,
    "provinceCode": "NAN",
    "districtCode": "VIN",
    "precinctCode": "DCUN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-NAN",
    "partnerName": "Carpla Service Nghệ An",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000205,
    "code": "CAR-NAN-01_51M65531",
    "name": "Carpla Service Thanh Hóa 51M65531",
    "address": "",
    "latitude": 19.833383,
    "longitude": 105.872312,
    "provinceCode": "THO",
    "districtCode": "DSO",
    "precinctCode": "DQUA",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-NAN",
    "partnerName": "Carpla Service Nghệ An",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000220,
    "code": "CAR-TBB_51_30F08194",
    "name": "Carpla Service Sơn La 30F08194",
    "address": "",
    "latitude": 21.368087,
    "longitude": 103.778539,
    "provinceCode": "SLA",
    "districtCode": "SLA",
    "precinctCode": "THIE",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-TBB",
    "partnerName": "Carpla Service Tây Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000221,
    "code": "CAR-ĐNB-03_30B43193",
    "name": "Carpla Service Đắk Lắk 30B43193",
    "address": "",
    "latitude": 12.788041,
    "longitude": 108.083757,
    "provinceCode": "DLA",
    "districtCode": "BMT",
    "precinctCode": "ETAM",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNG",
    "partnerName": "Carpla Service Đà Nẵng",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000222,
    "code": "CAR-CTO_21_51M74411",
    "name": "Carpla Service Vĩnh Long 51M74411",
    "address": "",
    "latitude": 10.188154,
    "longitude": 105.94471,
    "provinceCode": "VLO",
    "districtCode": "LHO",
    "precinctCode": "THAN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-CTO",
    "partnerName": "Carpla Service Cần Thơ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000223,
    "code": "CAR-CTO_21_51M74412",
    "name": "Carpla Service Vĩnh Long 51M74412",
    "address": "",
    "latitude": 10.197196,
    "longitude": 106.00873,
    "provinceCode": "VLO",
    "districtCode": "LHO",
    "precinctCode": "THAN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-CTO",
    "partnerName": "Carpla Service Cần Thơ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000224,
    "code": "CAR-CTO_21_51M74413",
    "name": "Carpla Service Vĩnh Long 51M74413",
    "address": "",
    "latitude": 10.22051,
    "longitude": 105.933118,
    "provinceCode": "VLO",
    "districtCode": "LHO",
    "precinctCode": "THAN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-CTO",
    "partnerName": "Carpla Service Cần Thơ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000225,
    "code": "CAR-CTO_21_51M74414",
    "name": "Carpla Service Vĩnh Long 51M74414",
    "address": "",
    "latitude": 10.234587,
    "longitude": 105.951944,
    "provinceCode": "VLO",
    "districtCode": "LHO",
    "precinctCode": "THAN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-CTO",
    "partnerName": "Carpla Service Cần Thơ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000226,
    "code": "CAR-HN-06_51M63981",
    "name": "Carpla Service Giải Phóng 51M63981",
    "address": "",
    "latitude": 20.99191,
    "longitude": 105.838453,
    "provinceCode": "HNO",
    "districtCode": "HMA",
    "precinctCode": "TMA0",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HN",
    "partnerName": "Carpla Service Hà Nội",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000227,
    "code": "CAR-HN_81_51M67583",
    "name": "Carpla Service Ninh Bình 51M67583",
    "address": "",
    "latitude": 20.216993,
    "longitude": 106.005342,
    "provinceCode": "NBI",
    "districtCode": "PHL",
    "precinctCode": "PNA",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HN",
    "partnerName": "Carpla Service Hà Nội",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000228,
    "code": "CAR-HN_81_30A60455",
    "name": "Carpla Service Ninh Bình 30A60455",
    "address": "",
    "latitude": 20.240542,
    "longitude": 106.030167,
    "provinceCode": "NBI",
    "districtCode": "PHL",
    "precinctCode": "PNA",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HN",
    "partnerName": "Carpla Service Hà Nội",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000229,
    "code": "CAR-ĐNG_21_51M-678.59",
    "name": "Carpla Service Gia Lai 51M-678.59",
    "address": "",
    "latitude": 13.829106,
    "longitude": 108.052854,
    "provinceCode": "GLA",
    "districtCode": "AKH",
    "precinctCode": "APHU",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNG",
    "partnerName": "Carpla Service Đà Nẵng",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000230,
    "code": "CAR-ĐNG_21_51M-741.43",
    "name": "Carpla Service Gia Lai 51M-741.43",
    "address": "",
    "latitude": 13.976432,
    "longitude": 108.022189,
    "provinceCode": "GLA",
    "districtCode": "AKH",
    "precinctCode": "APHU",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNG",
    "partnerName": "Carpla Service Đà Nẵng",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000231,
    "code": "CAR-ĐBB_71_51M74346",
    "name": "Carpla Service Hà Giang 51M74346",
    "address": "",
    "latitude": 22.981739,
    "longitude": 105.092729,
    "provinceCode": "TQU",
    "districtCode": "TQU",
    "precinctCode": "MXUA",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐBB",
    "partnerName": "Carpla Service Đông Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000232,
    "code": "CAR-CTO_101_30F43920",
    "name": "Carpla Service Đồng Tháp 30F43920",
    "address": "",
    "latitude": 10.54724,
    "longitude": 105.75322,
    "provinceCode": "DTH",
    "districtCode": "CAH",
    "precinctCode": "MNGA",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-CTO",
    "partnerName": "Carpla Service Cần Thơ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000233,
    "code": "CAR-HCM-01_51B-416.19",
    "name": "Carpla Service Phú Mỹ Hưng 51B-416.19",
    "address": "",
    "latitude": 10.727193,
    "longitude": 106.725263,
    "provinceCode": "HCM",
    "districtCode": "007",
    "precinctCode": "BTHU",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HCM",
    "partnerName": "Carpla Service Hồ Chí Minh",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000234,
    "code": "CAR-HCM_61_51M70516",
    "name": "Carpla Service Chế Lan Viên 51M70516",
    "address": "",
    "latitude": 10.79891,
    "longitude": 106.631732,
    "provinceCode": "HCM",
    "districtCode": "TPH",
    "precinctCode": "TTHN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HCM",
    "partnerName": "Carpla Service Hồ Chí Minh",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000235,
    "code": "CAR-ĐNB-01_51M65457",
    "name": "Carpla Service Vĩnh Phú - Bình Dương 51M65457",
    "address": "",
    "latitude": 10.875381,
    "longitude": 106.685382,
    "provinceCode": "BDU",
    "districtCode": "TAN",
    "precinctCode": "BHOA",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNB",
    "partnerName": "Carpla Service Đông Nam Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000236,
    "code": "CAR-HCM_101_51M-744.21",
    "name": "Carpla Service Đồng Nai 51M-744.21",
    "address": "",
    "latitude": 10.993716,
    "longitude": 107.029419,
    "provinceCode": "BPH",
    "districtCode": "BGM",
    "precinctCode": "LBIN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNB",
    "partnerName": "Carpla Service Đông Nam Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000237,
    "code": "CAR-HCM_101_51M-676.20",
    "name": "Carpla Service Đồng Nai 51M-676.20",
    "address": "",
    "latitude": 11.040228,
    "longitude": 106.882995,
    "provinceCode": "BPH",
    "districtCode": "BGM",
    "precinctCode": "LBIN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNB",
    "partnerName": "Carpla Service Đông Nam Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000238,
    "code": "CAR-HCM_81_51M78241",
    "name": "Carpla Service Tây Ninh 51M78241",
    "address": "",
    "latitude": 11.561724,
    "longitude": 106.073705,
    "provinceCode": "TNI",
    "districtCode": "TBI",
    "precinctCode": "THIE",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-TNB",
    "partnerName": "Carpla Service Tây Nam Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000239,
    "code": "CAR-HCM_81_51M67961",
    "name": "Carpla Service Tây Ninh 51M67961",
    "address": "",
    "latitude": 11.541037,
    "longitude": 106.009122,
    "provinceCode": "TNI",
    "districtCode": "TBI",
    "precinctCode": "THIE",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-TNB",
    "partnerName": "Carpla Service Tây Nam Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000240,
    "code": "CAR-HCM_71_51M67960",
    "name": "Carpla Service Bình Thuận 51M67960",
    "address": "",
    "latitude": 11.105059,
    "longitude": 108.018048,
    "provinceCode": "BTH",
    "districtCode": "HTB",
    "precinctCode": "HTHA",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNB",
    "partnerName": "Carpla Service Đông Nam Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000241,
    "code": "CAR-HCM_41_51M67744",
    "name": "Carpla Service Đà Lạt 51M67744",
    "address": "",
    "latitude": 11.951667,
    "longitude": 108.378752,
    "provinceCode": "LDO",
    "districtCode": "DLA",
    "precinctCode": "0003",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNB",
    "partnerName": "Carpla Service Đông Nam Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000242,
    "code": "CAR-HN-03_29H18831",
    "name": "Carpla Service Hải Phòng 29H18831",
    "address": "",
    "latitude": 20.838051,
    "longitude": 106.723255,
    "provinceCode": "HPH",
    "districtCode": "HAN",
    "precinctCode": "LDU",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐBB",
    "partnerName": "Carpla Service Đông Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000245,
    "code": "CAR-CTO_81_51M67671",
    "name": "Carpla Service An Giang( Long Xuyên) 51M67671",
    "address": "",
    "latitude": 10.455644,
    "longitude": 105.284702,
    "provinceCode": "AGI",
    "districtCode": "LXU",
    "precinctCode": "MXUY",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-CTO",
    "partnerName": "Carpla Service Cần Thơ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000247,
    "code": "CAR-HN-05_30G76835",
    "name": "Carpla Service Long Biên 30G76835",
    "address": "",
    "latitude": 21.066233,
    "longitude": 105.897509,
    "provinceCode": "HNO",
    "districtCode": "LBI",
    "precinctCode": "VHUN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HN",
    "partnerName": "Carpla Service Hà Nội",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000248,
    "code": "CAR-ĐBB_61_30G69434",
    "name": "Carpla Service Bắc Ninh 30G69434",
    "address": "",
    "latitude": 21.196211,
    "longitude": 106.047964,
    "provinceCode": "BNI",
    "districtCode": "BNI",
    "precinctCode": "KBAC",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐBB",
    "partnerName": "Carpla Service Đông Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000249,
    "code": "CAR-ĐBB_61_30H20150",
    "name": "Carpla Service Bắc Ninh 30H20150",
    "address": "",
    "latitude": 21.193386,
    "longitude": 106.082324,
    "provinceCode": "BNI",
    "districtCode": "BNI",
    "precinctCode": "KBAC",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐBB",
    "partnerName": "Carpla Service Đông Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000250,
    "code": "CAR-HN-05_30B35875",
    "name": "Carpla Service Long Biên 30B35875",
    "address": "",
    "latitude": 21.066811,
    "longitude": 105.887966,
    "provinceCode": "HNO",
    "districtCode": "LBI",
    "precinctCode": "VHUN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HN",
    "partnerName": "Carpla Service Hà Nội",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000251,
    "code": "CAR-ĐNG-01_30H-54906",
    "name": "Carpla Service Đà Nẵng 30H-54906",
    "address": "",
    "latitude": 16.003529,
    "longitude": 108.223236,
    "provinceCode": "DNA",
    "districtCode": "HVA",
    "precinctCode": "HPH0",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNG",
    "partnerName": "Carpla Service Đà Nẵng",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000252,
    "code": "CAR-ĐBB_51_51M-74487",
    "name": "Carpla Service Lạng Sơn 51M-74487",
    "address": "",
    "latitude": 21.809305,
    "longitude": 106.604807,
    "provinceCode": "LSO",
    "districtCode": "20",
    "precinctCode": "PKL",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐBB",
    "partnerName": "Carpla Service Đông Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000253,
    "code": "CAR-ĐBB_51_30B43198",
    "name": "Carpla Service Lạng Sơn 30B43198",
    "address": "",
    "latitude": 21.964171,
    "longitude": 106.612911,
    "provinceCode": "LSO",
    "districtCode": "20",
    "precinctCode": "PKL",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐBB",
    "partnerName": "Carpla Service Đông Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000254,
    "code": "CAR-NAN-02_51M65636",
    "name": "Carpla Service Nghệ An 51M65636",
    "address": "",
    "latitude": 18.709066,
    "longitude": 105.681361,
    "provinceCode": "NAN",
    "districtCode": "VIN",
    "precinctCode": "DCUN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-NAN",
    "partnerName": "Carpla Service Nghệ An",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000255,
    "code": "CAR-NAN-02_30H67689",
    "name": "Carpla Service Nghệ An 30H67689",
    "address": "",
    "latitude": 18.703678,
    "longitude": 105.652247,
    "provinceCode": "NAN",
    "districtCode": "VIN",
    "precinctCode": "DCUN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-NAN",
    "partnerName": "Carpla Service Nghệ An",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000256,
    "code": "CAR-NAN-02_30H04631",
    "name": "Carpla Service Nghệ An 30H04631",
    "address": "",
    "latitude": 18.697089,
    "longitude": 105.66945,
    "provinceCode": "NAN",
    "districtCode": "VIN",
    "precinctCode": "DCUN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-NAN",
    "partnerName": "Carpla Service Nghệ An",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000257,
    "code": "CAR-TBB_61_30B50191",
    "name": "Carpla Service Yên Bái 30B50191",
    "address": "",
    "latitude": 21.599102,
    "longitude": 104.70197,
    "provinceCode": "YBA",
    "districtCode": "YBA",
    "precinctCode": "ALAU",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-TBB",
    "partnerName": "Carpla Service Tây Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000258,
    "code": "CAR-HN-03_30E12680",
    "name": "Carpla Service Hải Phòng 30E12680",
    "address": "",
    "latitude": 20.835354,
    "longitude": 106.709942,
    "provinceCode": "HPH",
    "districtCode": "HAN",
    "precinctCode": "LDU",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐBB",
    "partnerName": "Carpla Service Đông Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000259,
    "code": "CAR-HN-06_30B-35944",
    "name": "Carpla Service Giải Phóng 30B-35944",
    "address": "",
    "latitude": 20.987689,
    "longitude": 105.849202,
    "provinceCode": "HNO",
    "districtCode": "HMA",
    "precinctCode": "TMA0",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HN",
    "partnerName": "Carpla Service Hà Nội",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000260,
    "code": "CAR-CTO_101_30B-431.72",
    "name": "Carpla Service Đồng Tháp 30B-431.72",
    "address": "",
    "latitude": 10.603292,
    "longitude": 105.667564,
    "provinceCode": "DTH",
    "districtCode": "CAH",
    "precinctCode": "MNGA",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-CTO",
    "partnerName": "Carpla Service Cần Thơ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000261,
    "code": "CAR-NAN-01_30A60190",
    "name": "Carpla Service Thanh Hóa 30A60190",
    "address": "",
    "latitude": 19.843223,
    "longitude": 105.599619,
    "provinceCode": "THO",
    "districtCode": "DSO",
    "precinctCode": "DQUA",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-NAN",
    "partnerName": "Carpla Service Nghệ An",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000262,
    "code": "CAR-HN-08_30B43153",
    "name": "Carpla Service Nam Định 30B43153",
    "address": "",
    "latitude": 20.42858,
    "longitude": 106.165215,
    "provinceCode": "NDI",
    "districtCode": "NDI",
    "precinctCode": "NML",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐBB",
    "partnerName": "Carpla Service Đông Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000263,
    "code": "CAR-NAN-01_30B35945",
    "name": "Carpla Service Thanh Hóa 30B35945",
    "address": "",
    "latitude": 19.758774,
    "longitude": 105.609749,
    "provinceCode": "THO",
    "districtCode": "DSO",
    "precinctCode": "DQUA",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-NAN",
    "partnerName": "Carpla Service Nghệ An",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000264,
    "code": "CAR-ĐNG_81_51M64230",
    "name": "Carpla Service Đắk Nông 51M64230",
    "address": "",
    "latitude": 12.05229,
    "longitude": 107.49807,
    "provinceCode": "DNO",
    "districtCode": "GNG",
    "precinctCode": "NTRU",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HCM",
    "partnerName": "Carpla Service Hồ Chí Minh",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000266,
    "code": "CAR-TBB_71_51M71658",
    "name": "Carpla Service Lai Châu 51M71658",
    "address": "",
    "latitude": 22.334689,
    "longitude": 103.636762,
    "provinceCode": "LCH",
    "districtCode": "LCH",
    "precinctCode": "TPHO",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-TBB",
    "partnerName": "Carpla Service Tây Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000267,
    "code": "CAR-NAN-01_36B50106",
    "name": "Carpla Service Thanh Hóa 36B50106",
    "address": "",
    "latitude": 19.907141,
    "longitude": 105.640879,
    "provinceCode": "THO",
    "districtCode": "DSO",
    "precinctCode": "DQUA",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-NAN",
    "partnerName": "Carpla Service Nghệ An",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000268,
    "code": "CAR-HN_81_30B-43207",
    "name": "Carpla Service Ninh Bình 30B-43207",
    "address": "",
    "latitude": 20.289063,
    "longitude": 105.951342,
    "provinceCode": "NBI",
    "districtCode": "PHL",
    "precinctCode": "PNA",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HN",
    "partnerName": "Carpla Service Hà Nội",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000269,
    "code": "CAR-TBB_71_30F87164",
    "name": "Carpla Service Lai Châu 30F87164",
    "address": "",
    "latitude": 22.406692,
    "longitude": 103.326426,
    "provinceCode": "LCH",
    "districtCode": "LCH",
    "precinctCode": "TPHO",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-TBB",
    "partnerName": "Carpla Service Tây Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000270,
    "code": "CAR-HCM_41_30B-43208",
    "name": "Carpla Service Đà Lạt 30B-43208",
    "address": "",
    "latitude": 11.854299,
    "longitude": 108.548254,
    "provinceCode": "LDO",
    "districtCode": "DLA",
    "precinctCode": "0003",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNB",
    "partnerName": "Carpla Service Đông Nam Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000271,
    "code": "CAR-ĐNG-01_30B-43179",
    "name": "Carpla Service Đà Nẵng 30B-43179",
    "address": "",
    "latitude": 15.986358,
    "longitude": 108.19681,
    "provinceCode": "DNA",
    "districtCode": "HVA",
    "precinctCode": "HPH0",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNG",
    "partnerName": "Carpla Service Đà Nẵng",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000272,
    "code": "CAR-ĐNG-01_51M-65649",
    "name": "Carpla Service Đà Nẵng 51M-65649",
    "address": "",
    "latitude": 15.970189,
    "longitude": 108.022471,
    "provinceCode": "DNA",
    "districtCode": "HVA",
    "precinctCode": "HPH0",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNG",
    "partnerName": "Carpla Service Đà Nẵng",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000273,
    "code": "CAR-HN_61_30B-43156",
    "name": "Carpla Service Thái Bình 30B-43156",
    "address": "",
    "latitude": 20.443088,
    "longitude": 106.345221,
    "provinceCode": "TBI",
    "districtCode": "TBI",
    "precinctCode": "THDA",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HN",
    "partnerName": "Carpla Service Hà Nội",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000274,
    "code": "CAR-HN_61_51M-67562",
    "name": "Carpla Service Thái Bình 51M-67562",
    "address": "",
    "latitude": 20.446522,
    "longitude": 106.338412,
    "provinceCode": "TBI",
    "districtCode": "TBI",
    "precinctCode": "THDA",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HN",
    "partnerName": "Carpla Service Hà Nội",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000275,
    "code": "CAR-CTO-01_30B43171",
    "name": "Carpla Service Cần Thơ 30B43171",
    "address": "",
    "latitude": 10.02313,
    "longitude": 105.83282,
    "provinceCode": "STR",
    "districtCode": "MTU",
    "precinctCode": "HPHU",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-CTO",
    "partnerName": "Carpla Service Cần Thơ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000276,
    "code": "CAR-CTO-01_30B43206",
    "name": "Carpla Service Cần Thơ 30B43206",
    "address": "",
    "latitude": 9.981956,
    "longitude": 105.821582,
    "provinceCode": "STR",
    "districtCode": "MTU",
    "precinctCode": "HPHU",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-CTO",
    "partnerName": "Carpla Service Cần Thơ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000277,
    "code": "CAR-TBB_61_30B50112",
    "name": "Carpla Service Yên Bái 30B50112",
    "address": "",
    "latitude": 21.849003,
    "longitude": 104.79815,
    "provinceCode": "YBA",
    "districtCode": "YBA",
    "precinctCode": "ALAU",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-TBB",
    "partnerName": "Carpla Service Tây Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000278,
    "code": "CAR-ĐNB-02_30B43249",
    "name": "Carpla Service Bình Phước 30B43249",
    "address": "",
    "latitude": 11.502158,
    "longitude": 106.716797,
    "provinceCode": "BPH",
    "districtCode": "PLN",
    "precinctCode": "BPHU",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNB",
    "partnerName": "Carpla Service Đông Nam Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000279,
    "code": "CAR-ĐNG_41_30B43204",
    "name": "Carpla Service Quảng Ngãi 30B43204",
    "address": "",
    "latitude": 15.074807,
    "longitude": 108.660322,
    "provinceCode": "QNG",
    "districtCode": "QNG",
    "precinctCode": "TQTR",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNG",
    "partnerName": "Carpla Service Đà Nẵng",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000280,
    "code": "CAR-ĐNG_41_30K36448",
    "name": "Carpla Service Quảng Ngãi 30K36448",
    "address": "",
    "latitude": 14.974584,
    "longitude": 108.822389,
    "provinceCode": "QNG",
    "districtCode": "QNG",
    "precinctCode": "TQTR",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNG",
    "partnerName": "Carpla Service Đà Nẵng",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000281,
    "code": "CAR-HCM_121_30G-713.49",
    "name": "Carpla Service Tiền Giang 30G-713.49",
    "address": "",
    "latitude": 10.406387,
    "longitude": 106.333097,
    "provinceCode": "TGI",
    "districtCode": "MTH",
    "precinctCode": "TRAN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-TNB",
    "partnerName": "Carpla Service Tây Nam Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000282,
    "code": "CAR-HCM_121_30G-876.84",
    "name": "Carpla Service Tiền Giang 30G-876.84",
    "address": "",
    "latitude": 10.37615,
    "longitude": 106.340034,
    "provinceCode": "TGI",
    "districtCode": "MTH",
    "precinctCode": "TRAN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-TNB",
    "partnerName": "Carpla Service Tây Nam Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000283,
    "code": "CAR-ĐNB-03_30B-43205",
    "name": "Carpla Service Đắk Lắk 30B-43205",
    "address": "",
    "latitude": 12.584661,
    "longitude": 107.88707,
    "provinceCode": "DLA",
    "districtCode": "BMT",
    "precinctCode": "ETAM",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNG",
    "partnerName": "Carpla Service Đà Nẵng",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000284,
    "code": "CAR-NAN-03_30B43176",
    "name": "Carpla Service Hà Tĩnh 30B43176",
    "address": "",
    "latitude": 18.192588,
    "longitude": 105.802817,
    "provinceCode": "HTI",
    "districtCode": "CXU",
    "precinctCode": "CBIN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-NAN",
    "partnerName": "Carpla Service Nghệ An",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000285,
    "code": "CAR-NAN-03_30B50145",
    "name": "Carpla Service Hà Tĩnh 30B50145",
    "address": "",
    "latitude": 18.14822,
    "longitude": 105.934756,
    "provinceCode": "HTI",
    "districtCode": "CXU",
    "precinctCode": "CBIN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-NAN",
    "partnerName": "Carpla Service Nghệ An",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000286,
    "code": "CAR-HN-10_30B50150",
    "name": "Carpla Service Hòa Bình 30B50150",
    "address": "",
    "latitude": 20.743534,
    "longitude": 105.231468,
    "provinceCode": "HBI",
    "districtCode": "HBI",
    "precinctCode": "HBIN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-TBB",
    "partnerName": "Carpla Service Tây Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000287,
    "code": "CAR-HCM_61_30B43183",
    "name": "Carpla Service Chế Lan Viên 30B43183",
    "address": "",
    "latitude": 10.813433,
    "longitude": 106.623666,
    "provinceCode": "HCM",
    "districtCode": "TPH",
    "precinctCode": "TTHN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HCM",
    "partnerName": "Carpla Service Hồ Chí Minh",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000288,
    "code": "CAR-HN-08_30B50101",
    "name": "Carpla Service Nam Định 30B50101",
    "address": "",
    "latitude": 20.376508,
    "longitude": 106.168671,
    "provinceCode": "NDI",
    "districtCode": "NDI",
    "precinctCode": "NML",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐBB",
    "partnerName": "Carpla Service Đông Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000289,
    "code": "CAR-HN_21_30M-43184",
    "name": "Carpla Service Hà Nam 30M-43184",
    "address": "",
    "latitude": 20.532145,
    "longitude": 105.891375,
    "provinceCode": "HNA",
    "districtCode": "PLY",
    "precinctCode": "PVAN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HN",
    "partnerName": "Carpla Service Hà Nội",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000292,
    "code": "CAR-HN-01_30B43163",
    "name": "Carpla Service Thái Nguyên 30B43163",
    "address": "",
    "latitude": 21.675454,
    "longitude": 105.732538,
    "provinceCode": "TNG",
    "districtCode": "TNG",
    "precinctCode": "GSAN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐBB",
    "partnerName": "Carpla Service Đông Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000293,
    "code": "CAR-HN-01_30B50142",
    "name": "Carpla Service Thái Nguyên 30B50142",
    "address": "",
    "latitude": 21.6388,
    "longitude": 105.991122,
    "provinceCode": "TNG",
    "districtCode": "TNG",
    "precinctCode": "GSAN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐBB",
    "partnerName": "Carpla Service Đông Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000331,
    "code": "CAR-HN-09_30G36030",
    "name": "Carpla Service Hưng Yên 30G36030",
    "address": "",
    "latitude": 20.658773,
    "longitude": 106.05479,
    "provinceCode": "HYE",
    "districtCode": "HYE",
    "precinctCode": "HYEN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HN",
    "partnerName": "Carpla Service Hà Nội",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000332,
    "code": "CAR-HN-09_51M64351",
    "name": "Carpla Service Hưng Yên 51M64351",
    "address": "",
    "latitude": 20.676063,
    "longitude": 106.066018,
    "provinceCode": "HYE",
    "districtCode": "HYE",
    "precinctCode": "HYEN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HN",
    "partnerName": "Carpla Service Hà Nội",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000333,
    "code": "CAR-HN-09_30B50114",
    "name": "Carpla Service Hưng Yên 30B50114",
    "address": "",
    "latitude": 20.671883,
    "longitude": 106.047164,
    "provinceCode": "HYE",
    "districtCode": "HYE",
    "precinctCode": "HYEN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HN",
    "partnerName": "Carpla Service Hà Nội",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000351,
    "code": "CAR-ĐNG_51_51M-71815",
    "name": "Carpla Service Quảng Nam 51M-71815",
    "address": "",
    "latitude": 15.460504,
    "longitude": 108.344815,
    "provinceCode": "QNA",
    "districtCode": "TKY",
    "precinctCode": "20335",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNG",
    "partnerName": "Carpla Service Đà Nẵng",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000352,
    "code": "CAR-ĐNG_51_30B-42303",
    "name": "Carpla Service Quảng Nam 30B-42303",
    "address": "",
    "latitude": 15.581842,
    "longitude": 108.47626,
    "provinceCode": "QNA",
    "districtCode": "TKY",
    "precinctCode": "20335",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNG",
    "partnerName": "Carpla Service Đà Nẵng",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000353,
    "code": "CAR-ĐNG_31_30B-432.09",
    "name": "Carpla Service Ninh Thuận 30B-432.09",
    "address": "",
    "latitude": 11.552746,
    "longitude": 108.985028,
    "provinceCode": "NTH",
    "districtCode": "TNA",
    "precinctCode": "PDIN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNG",
    "partnerName": "Carpla Service Đà Nẵng",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000354,
    "code": "CAR-ĐNG_31_51M64100",
    "name": "Carpla Service Ninh Thuận 51M64100",
    "address": "",
    "latitude": 11.650781,
    "longitude": 109.044115,
    "provinceCode": "NTH",
    "districtCode": "TNA",
    "precinctCode": "PDIN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNG",
    "partnerName": "Carpla Service Đà Nẵng",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000355,
    "code": "TEST_01_99A97026",
    "name": "Trạm TEST (Không chọn) 99A97026",
    "address": "",
    "latitude": 21.007108,
    "longitude": 105.780771,
    "provinceCode": "HNO",
    "districtCode": "CGI",
    "precinctCode": "TLIE",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "TEST",
    "partnerName": "PARTNER TEST",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000356,
    "code": "CAR-ĐBB_61_30B50149",
    "name": "Carpla Service Bắc Ninh 30B50149",
    "address": "",
    "latitude": 21.187446,
    "longitude": 106.061582,
    "provinceCode": "BNI",
    "districtCode": "BNI",
    "precinctCode": "KBAC",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐBB",
    "partnerName": "Carpla Service Đông Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000359,
    "code": "CAR-ĐNG_81_30B43242",
    "name": "Carpla Service Đắk Nông 30B43242",
    "address": "",
    "latitude": 11.92377,
    "longitude": 107.828312,
    "provinceCode": "DNO",
    "districtCode": "GNG",
    "precinctCode": "NTRU",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HCM",
    "partnerName": "Carpla Service Hồ Chí Minh",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000360,
    "code": "CAR-HCM_41_30B-50158",
    "name": "Carpla Service Đà Lạt 30B-50158",
    "address": "",
    "latitude": 12.022588,
    "longitude": 108.562497,
    "provinceCode": "LDO",
    "districtCode": "DLA",
    "precinctCode": "0003",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNB",
    "partnerName": "Carpla Service Đông Nam Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000361,
    "code": "CAR-ĐNG-02_30F78304",
    "name": "Carpla Service Nha Trang 30F78304",
    "address": "",
    "latitude": 12.386048,
    "longitude": 109.136457,
    "provinceCode": "KHO",
    "districtCode": "NTR",
    "precinctCode": "VTHN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNG",
    "partnerName": "Carpla Service Đà Nẵng",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000362,
    "code": "CAR-HCM_81_30B43211",
    "name": "Carpla Service Tây Ninh 30B43211",
    "address": "",
    "latitude": 11.549693,
    "longitude": 105.993676,
    "provinceCode": "TNI",
    "districtCode": "TBI",
    "precinctCode": "THIE",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-TNB",
    "partnerName": "Carpla Service Tây Nam Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000363,
    "code": "CAR-CTO_11_30B-43213",
    "name": "Carpla Service Cà Mau 30B-43213",
    "address": "",
    "latitude": 8.974761,
    "longitude": 105.135188,
    "provinceCode": "CMA",
    "districtCode": "CMA",
    "precinctCode": "LVLA",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-CTO",
    "partnerName": "Carpla Service Cần Thơ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000366,
    "code": "CAR-HN-05_30B50179",
    "name": "Carpla Service Long Biên 30B50179",
    "address": "",
    "latitude": 21.039676,
    "longitude": 105.896834,
    "provinceCode": "HNO",
    "districtCode": "LBI",
    "precinctCode": "VHUN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HN",
    "partnerName": "Carpla Service Hà Nội",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000380,
    "code": "CAR-HCM-01_51M-640.83",
    "name": "Carpla Service Phú Mỹ Hưng 51M-640.83",
    "address": "",
    "latitude": 10.741879,
    "longitude": 106.710095,
    "provinceCode": "HCM",
    "districtCode": "007",
    "precinctCode": "BTHU",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HCM",
    "partnerName": "Carpla Service Hồ Chí Minh",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000381,
    "code": "CAR-HCM-01_30B-501.41",
    "name": "Carpla Service Phú Mỹ Hưng 30B-501.41",
    "address": "",
    "latitude": 10.742823,
    "longitude": 106.723327,
    "provinceCode": "HCM",
    "districtCode": "007",
    "precinctCode": "BTHU",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HCM",
    "partnerName": "Carpla Service Hồ Chí Minh",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000382,
    "code": "CAR-HCM-01_30B-432.41",
    "name": "Carpla Service Phú Mỹ Hưng 30B-432.41",
    "address": "",
    "latitude": 10.751052,
    "longitude": 106.721826,
    "provinceCode": "HCM",
    "districtCode": "007",
    "precinctCode": "BTHU",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HCM",
    "partnerName": "Carpla Service Hồ Chí Minh",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000383,
    "code": "CAR-CTO_21_30B55924",
    "name": "Carpla Service Vĩnh Long 30B55924",
    "address": "",
    "latitude": 10.213952,
    "longitude": 105.961336,
    "provinceCode": "VLO",
    "districtCode": "LHO",
    "precinctCode": "THAN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-CTO",
    "partnerName": "Carpla Service Cần Thơ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000384,
    "code": "CAR-HCM_101_30B-559.05",
    "name": "Carpla Service Đồng Nai 30B-559.05",
    "address": "",
    "latitude": 10.961762,
    "longitude": 106.867131,
    "provinceCode": "BPH",
    "districtCode": "BGM",
    "precinctCode": "LBIN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNB",
    "partnerName": "Carpla Service Đông Nam Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000385,
    "code": "CAR-HCM_101_30B-432.02",
    "name": "Carpla Service Đồng Nai 30B-432.02",
    "address": "",
    "latitude": 10.974305,
    "longitude": 106.880338,
    "provinceCode": "BPH",
    "districtCode": "BGM",
    "precinctCode": "LBIN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNB",
    "partnerName": "Carpla Service Đông Nam Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000386,
    "code": "CAR-HN_21_30B-50129",
    "name": "Carpla Service Hà Nam 30B-50129",
    "address": "",
    "latitude": 20.554415,
    "longitude": 105.902541,
    "provinceCode": "HNA",
    "districtCode": "PLY",
    "precinctCode": "PVAN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HN",
    "partnerName": "Carpla Service Hà Nội",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000387,
    "code": "CAR-CTO_101_30B-558.63",
    "name": "Carpla Service Đồng Tháp 30B-558.63",
    "address": "",
    "latitude": 10.62772,
    "longitude": 105.533303,
    "provinceCode": "DTH",
    "districtCode": "CAH",
    "precinctCode": "MNGA",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-CTO",
    "partnerName": "Carpla Service Cần Thơ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000388,
    "code": "CAR-CTO_101_30B-559.22",
    "name": "Carpla Service Đồng Tháp 30B-559.22",
    "address": "",
    "latitude": 10.574149,
    "longitude": 105.458254,
    "provinceCode": "DTH",
    "districtCode": "CAH",
    "precinctCode": "MNGA",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-CTO",
    "partnerName": "Carpla Service Cần Thơ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000427,
    "code": "CAR-ĐNB-02_30B50131",
    "name": "Carpla Service Bình Phước 30B50131",
    "address": "",
    "latitude": 11.667831,
    "longitude": 106.829251,
    "provinceCode": "BPH",
    "districtCode": "PLN",
    "precinctCode": "BPHU",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNB",
    "partnerName": "Carpla Service Đông Nam Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000428,
    "code": "CAR-HN-06_30B-50118",
    "name": "Carpla Service Giải Phóng 30B-50118",
    "address": "",
    "latitude": 20.984485,
    "longitude": 105.842716,
    "provinceCode": "HNO",
    "districtCode": "HMA",
    "precinctCode": "TMA0",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HN",
    "partnerName": "Carpla Service Hà Nội",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000429,
    "code": "CAR-HN-06_30B-50159",
    "name": "Carpla Service Giải Phóng 30B-50159",
    "address": "",
    "latitude": 20.982403,
    "longitude": 105.848637,
    "provinceCode": "HNO",
    "districtCode": "HMA",
    "precinctCode": "TMA0",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HN",
    "partnerName": "Carpla Service Hà Nội",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000431,
    "code": "CAR-ĐNG_21_30B50175",
    "name": "Carpla Service Gia Lai 30B50175",
    "address": "",
    "latitude": 13.973131,
    "longitude": 108.044814,
    "provinceCode": "GLA",
    "districtCode": "AKH",
    "precinctCode": "APHU",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNG",
    "partnerName": "Carpla Service Đà Nẵng",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000478,
    "code": "CAR-TBB_51_30B43216",
    "name": "Carpla Service Sơn La 30B43216",
    "address": "",
    "latitude": 21.443134,
    "longitude": 104.053549,
    "provinceCode": "SLA",
    "districtCode": "SLA",
    "precinctCode": "THIE",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-TBB",
    "partnerName": "Carpla Service Tây Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000479,
    "code": "CAR-TBB_51_51M78179",
    "name": "Carpla Service Sơn La 51M78179",
    "address": "",
    "latitude": 21.144511,
    "longitude": 104.026758,
    "provinceCode": "SLA",
    "districtCode": "SLA",
    "precinctCode": "THIE",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-TBB",
    "partnerName": "Carpla Service Tây Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000500,
    "code": "CAR-CTO-01_30B50153",
    "name": "Carpla Service Cần Thơ 30B50153",
    "address": "",
    "latitude": 10.02486,
    "longitude": 105.798236,
    "provinceCode": "STR",
    "districtCode": "MTU",
    "precinctCode": "HPHU",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-CTO",
    "partnerName": "Carpla Service Cần Thơ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000502,
    "code": "CAR-ĐBB_61_30G36605",
    "name": "Carpla Service Bắc Ninh 30G36605",
    "address": "",
    "latitude": 21.183637,
    "longitude": 106.07433,
    "provinceCode": "BNI",
    "districtCode": "BNI",
    "precinctCode": "KBAC",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐBB",
    "partnerName": "Carpla Service Đông Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000529,
    "code": "CAR-HCM_31_30B43246",
    "name": "Carpla Service Long An 30B43246",
    "address": "",
    "latitude": 10.552459,
    "longitude": 106.425065,
    "provinceCode": "LAN",
    "districtCode": "CGI",
    "precinctCode": "LOAN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-TNB",
    "partnerName": "Carpla Service Tây Nam Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000823,
    "code": "CAR-NAN-02_30B-501.57",
    "name": "Carpla Service Nghệ An 30B-501.57",
    "address": "",
    "latitude": 18.613653,
    "longitude": 105.531604,
    "provinceCode": "NAN",
    "districtCode": "VIN",
    "precinctCode": "DCUN",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-NAN",
    "partnerName": "Carpla Service Nghệ An",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000871,
    "code": "CAR-ĐNG_21_30B-413.92",
    "name": "Carpla Service Gia Lai 30B-413.92",
    "address": "",
    "latitude": 14.113535,
    "longitude": 107.973723,
    "provinceCode": "GLA",
    "districtCode": "AKH",
    "precinctCode": "APHU",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNG",
    "partnerName": "Carpla Service Đà Nẵng",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000877,
    "code": "Carpla_HN_01_51M65882",
    "name": "Carpla Service Hà Đông 51M65882",
    "address": "",
    "latitude": 20.957199,
    "longitude": 105.764656,
    "provinceCode": "HNO",
    "districtCode": "HDO",
    "precinctCode": "YNGH",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HN",
    "partnerName": "Carpla Service Hà Nội",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000878,
    "code": "Carpla_HN_01_30B50148",
    "name": "Carpla Service Hà Đông 30B50148",
    "address": "",
    "latitude": 20.950347,
    "longitude": 105.734698,
    "provinceCode": "HNO",
    "districtCode": "HDO",
    "precinctCode": "YNGH",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HN",
    "partnerName": "Carpla Service Hà Nội",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000879,
    "code": "Carpla_HN_01_30B50125",
    "name": "Carpla Service Hà Đông 30B50125",
    "address": "",
    "latitude": 20.942681,
    "longitude": 105.753163,
    "provinceCode": "HNO",
    "districtCode": "HDO",
    "precinctCode": "YNGH",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HN",
    "partnerName": "Carpla Service Hà Nội",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000887,
    "code": "CAR-HN-02_30B43149",
    "name": "Carpla Service Vĩnh Phúc 30B43149",
    "address": "",
    "latitude": 21.329298,
    "longitude": 105.5924,
    "provinceCode": "VPH",
    "districtCode": "VYE",
    "precinctCode": "NQUY",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-TBB",
    "partnerName": "Carpla Service Tây Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000888,
    "code": "CAR-HN-02_30B55883",
    "name": "Carpla Service Vĩnh Phúc 30B55883",
    "address": "",
    "latitude": 21.306624,
    "longitude": 105.585477,
    "provinceCode": "VPH",
    "districtCode": "VYE",
    "precinctCode": "NQUY",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-TBB",
    "partnerName": "Carpla Service Tây Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10000919,
    "code": "CAR-HCM-04_30B-432.35",
    "name": "Carpla Service Vũng Tàu 30B-432.35",
    "address": "",
    "latitude": 10.417069,
    "longitude": 106.952433,
    "provinceCode": "BRV",
    "districtCode": "VTA",
    "precinctCode": "0006",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐNB",
    "partnerName": "Carpla Service Đông Nam Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10001031,
    "code": "PT9D3243AB_4905_99A11111",
    "name": "Trạm test 01 99A11111",
    "address": "",
    "latitude": 21.021125,
    "longitude": 105.851843,
    "provinceCode": "HNO",
    "districtCode": "HKI",
    "precinctCode": "CNAM",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "PT9D3243AB",
    "partnerName": "Trạm test 01",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10001050,
    "code": "CAR-HN_81_30B50144",
    "name": "Carpla Service Ninh Bình 30B50144",
    "address": "",
    "latitude": 20.244197,
    "longitude": 105.792701,
    "provinceCode": "NBI",
    "districtCode": "PHL",
    "precinctCode": "PNA",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-HN",
    "partnerName": "Carpla Service Hà Nội",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10001051,
    "code": "PTA8868E2E_7245_30A62388",
    "name": "hỗ trợ từ xa 30A62388",
    "address": "",
    "latitude": 21.030597,
    "longitude": 105.855345,
    "provinceCode": "HNO",
    "districtCode": "HKI",
    "precinctCode": null,
    "areaType": null,
    "partnerId": null,
    "partnerCode": "PTA8868E2E",
    "partnerName": "hỗ trợ từ xa",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10001059,
    "code": "CAR-HN-04_30B43164",
    "name": "Carpla Service Quảng Ninh 30B43164",
    "address": "",
    "latitude": 20.97396,
    "longitude": 106.98593,
    "provinceCode": "QNI",
    "districtCode": "HLO",
    "precinctCode": "TCHA",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐBB",
    "partnerName": "Carpla Service Đông Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10001060,
    "code": "CAR-HN-04_30B43185",
    "name": "Carpla Service Quảng Ninh 30B43185",
    "address": "",
    "latitude": 20.928283,
    "longitude": 106.984566,
    "provinceCode": "QNI",
    "districtCode": "HLO",
    "precinctCode": "TCHA",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐBB",
    "partnerName": "Carpla Service Đông Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10001061,
    "code": "CAR-HN-04_29H18086",
    "name": "Carpla Service Quảng Ninh 29H18086",
    "address": "",
    "latitude": 21.007411,
    "longitude": 106.829488,
    "provinceCode": "QNI",
    "districtCode": "HLO",
    "precinctCode": "TCHA",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐBB",
    "partnerName": "Carpla Service Đông Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  },
  {
    "id": 10001062,
    "code": "CAR-HN-04_30B50192",
    "name": "Carpla Service Quảng Ninh 30B50192",
    "address": "",
    "latitude": 20.969259,
    "longitude": 107.164615,
    "provinceCode": "QNI",
    "districtCode": "HLO",
    "precinctCode": "TCHA",
    "areaType": null,
    "partnerId": null,
    "partnerCode": "CAR-ĐBB",
    "partnerName": "Carpla Service Đông Bắc Bộ",
    "partnerType": "INTERNAL",
    "signingDate": null
  }
]
;
